### ISSUE TITLE
大量圣遗物导入后程序缓慢的优化

### ISSUE THREAD

**Issue by morlay** [morlay/genshintools#11]

**Comment by Escheee** [comment]
发现主要问题可能在这里，

```
    var uid = BlocAuth.watch(context).state.chosenUid();

    useObservableEffect(() {
      final blocAuth = BlocAuth.read(context);

      if (blocAuth.state.hasLogon()) {
        return Rx.fromCallable(() => BlocGameData.read(context).syncGameInfo(
              blocAuth.state.authedClient(),
              blocAuth.state.chosenUid(),
            ));
      }
    }, [uid]);
```
我理解原本代码逻辑是uid发生变化，才通过MiHoYoBBS进行信息同步
信息同步后获取的角色圣遗物信息会和BlocGameData的数据比对，syncGameInfo()很耗时

但是，目前useObservableEffect无论uid是否变化都会执行，每次切换到今日或者角色都会进行信息同步，尤其角色页面信息同步后比对更加耗时

**Comment by morlay** [comment]
和拉数据无关

这里 https://github.com/morlay/genshintools/blob/main/packages/genshindb/lib/src/types/artifact.dart#L199
计算缓存应该放更全局的地方，之前放到 class 上的。
用的 freeze，所有 class 是 imutable，会复制，缓存就丢了。
